import {state} from "./state.js";
import {getBounds} from "./compiler.js";
import {download,safeLuaString,slug} from "./utils.js";

function sorted(){
  return [...state.voxels.values()].sort((a,b)=>a.y-b.y||a.x-b.x||a.z-b.z);
}
export function exportWorldEdit(){
  const b=getBounds();
  let out="5:return {\n";
  for(const v of sorted()){
    out+=`  {x=${v.x-b.min[0]}, y=${v.y-b.min[1]}, z=${v.z-b.min[2]}, name=${safeLuaString(v.mat)}, param1=0, param2=${v.param2||0}},\n`;
  }
  out+="}\n";
  download(`${slug(state.plan?.name||"structure")}.we`,out);
}
export function exportLua(){
  const b=getBounds(),name=slug(state.plan?.name||"structure");
  const nodes=sorted().map(v=>`  {${v.x-b.min[0]},${v.y-b.min[1]},${v.z-b.min[2]},${safeLuaString(v.mat)},${v.param2||0}}`).join(",\n");
  const out=`-- Generated by Voxel Architect Studio
local DATA = {
${nodes}
}

function voxelbuild_place(origin)
  origin = vector.round(origin)
  for _, n in ipairs(DATA) do
    core.set_node({
      x = origin.x + n[1],
      y = origin.y + n[2],
      z = origin.z + n[3]
    }, {name = n[4], param2 = n[5] or 0})
  end
end
`;
  download(`${name}_place.lua`,out);
}
export function exportCompiledJSON(){
  const b=getBounds();
  const nodes=[...state.voxels.values()].map(v=>({x:v.x-b.min[0],y:v.y-b.min[1],z:v.z-b.min[2],name:v.mat,param2:v.param2||0}));
  download(`${slug(state.plan?.name||"structure")}_voxels.json`,JSON.stringify({
    format:"voxelbuild/compiled-1",name:state.plan?.name||"structure",size:b.size,nodes
  },null,2),"application/json");
}
